name: Continuous Integration

on: [pull_request]


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      - name: Cache pip dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          service_account_key: ${{ secrets.GCLOUD_JSON }}
          project_id: lmumlops-427510
      - name: Authenticate with GCP
        run: |
          echo "${{ secrets.GCLOUD_JSON }}" > gcloud.json
          echo "GOOGLE_APPLICATION_CREDENTIALS=${PWD}/gcloud.json" >> $GITHUB_ENV
          gcloud auth activate-service-account --key-file=${{ secrets.GCLOUD_JSON }}
      - name: Get data
        run: |
          pip install dvc
          pip install dvc-gs
          dvc pull 
      - name: Install dependencies
        run: |
          pip install pytest
          pip install -r requirements.txt
      - name: Run tests
        run: pytest tests/